<a href="https://colab.research.google.com/github/MohammadDanish099/DEEP-LEARNING-BACKPROPAGATION/blob/main/ann_Backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

# Activation functions
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Dataset (XOR)
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[1],[1],[0]])

# Network structure
input_neurons = 2
hidden_neurons = 3
output_neurons = 1

# Initialize weights
np.random.seed(1)
W1 = np.random.uniform(-1,1,(input_neurons, hidden_neurons))
W2 = np.random.uniform(-1,1,(hidden_neurons, output_neurons))

print("Initial Weights:")
print("W1:\n", W1)
print("W2:\n", W2)

# ---------- BEFORE TRAINING ----------
hidden = sigmoid(np.dot(X, W1))
output = sigmoid(np.dot(hidden, W2))

print("\nPredicted Output (Before Training):")
print(output)

# Loss before training
loss = np.mean((Y - output)**2)
print("\nInitial Loss:", loss)

# ---------- TRAINING ----------
lr = 0.5
epochs = 5000

for i in range(epochs):

    # Forward pass
    hidden = sigmoid(np.dot(X, W1))
    output = sigmoid(np.dot(hidden, W2))

    # Error
    error = Y - output

    # Backpropagation
    d_output = error * sigmoid_derivative(output)
    hidden_error = d_output.dot(W2.T)
    d_hidden = hidden_error * sigmoid_derivative(hidden)

    # Update weights
    W2 += hidden.T.dot(d_output) * lr
    W1 += X.T.dot(d_hidden) * lr

# ---------- AFTER TRAINING ----------
print("\nUpdated Weights:")
print("W1:\n", W1)
print("W2:\n", W2)

# Final prediction
hidden = sigmoid(np.dot(X, W1))
final_output = sigmoid(np.dot(hidden, W2))

print("\nPredicted Output (After Training):")
print(final_output)

# Final loss
final_loss = np.mean((Y - final_output)**2)
print("\nFinal Loss:", final_loss)

Initial Weights:
W1:
 [[-0.16595599  0.44064899 -0.99977125]
 [-0.39533485 -0.70648822 -0.81532281]]
W2:
 [[-0.62747958]
 [-0.30887855]
 [-0.20646505]]

Predicted Output (Before Training):
[[0.36091117]
 [0.3970195 ]
 [0.3702305 ]
 [0.40350728]]

Initial Loss: 0.26331752528341845

Updated Weights:
W1:
 [[-8.17825475  1.74936904 -5.31137004]
 [ 1.7152145  -8.23410935 -5.49428037]]
W2:
 [[  3.71945904]
 [  3.71693377]
 [-13.44844765]]

Predicted Output (After Training):
[[0.04715432]
 [0.95681929]
 [0.95694863]
 [0.50279651]]

Final Loss: 0.06468646380130104
