<a href="https://colab.research.google.com/github/MohammadDanish099/DEEP-LEARNING-BACKPROPAGATION/blob/main/CNN_Backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# ---------- FUNCTIONS ----------
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

def conv2d(image, kernel):
    k = kernel.shape[0]
    output_size = image.shape[0] - k + 1
    result = np.zeros((output_size, output_size))

    for i in range(output_size):
        for j in range(output_size):
            region = image[i:i+k, j:j+k]
            result[i,j] = np.sum(region * kernel)
    return result

# ---------- INPUT ----------
image = np.array([
    [1,2,3,0,1],
    [0,1,2,3,1],
    [1,2,1,0,0],
    [0,1,2,1,2],
    [1,0,1,2,1]
])

target = np.array([[1]])

# ---------- INITIAL WEIGHTS ----------
np.random.seed(1)
kernel = np.random.randn(3,3)
fc_weights = np.random.randn(9,1)

print("Initial Kernel:\n", kernel)
print("\nInitial FC Weights:\n", fc_weights)

# ---------- BEFORE TRAINING ----------
conv_out = conv2d(image, kernel)
activated = relu(conv_out)
flatten = activated.reshape(1,-1)
output = flatten.dot(fc_weights)

print("\nOutput Before Training:\n", output)

loss = np.mean((target - output)**2)
print("\nInitial Loss:", loss)

# ---------- TRAINING ----------
lr = 0.01
epochs = 200

for epoch in range(epochs):

    # Forward
    conv_out = conv2d(image, kernel)
    activated = relu(conv_out)
    flatten = activated.reshape(1,-1)
    output = flatten.dot(fc_weights)

    # Loss
    error = target - output

    # Backprop
    d_output = error
    d_fc = flatten.T.dot(d_output)

    d_flat = d_output.dot(fc_weights.T)
    d_act = d_flat.reshape(activated.shape) * relu_derivative(activated)

    # Update
    fc_weights += lr * d_fc
    kernel += lr * np.ones_like(kernel) * np.mean(d_act)

# ---------- AFTER TRAINING ----------
print("\nUpdated Kernel:\n", kernel)
print("\nUpdated FC Weights:\n", fc_weights)

conv_out = conv2d(image, kernel)
activated = relu(conv_out)
flatten = activated.reshape(1,-1)
final_output = flatten.dot(fc_weights)

print("\nFinal Output:\n", final_output)

final_loss = np.mean((target - final_output)**2)
print("\nFinal Loss:", final_loss)

Initial Kernel:
 [[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]]

Initial FC Weights:
 [[-0.24937038]
 [ 1.46210794]
 [-2.06014071]
 [-0.3224172 ]
 [-0.38405435]
 [ 1.13376944]
 [-1.09989127]
 [-0.17242821]
 [-0.87785842]]

Output Before Training:
 [[-5.27778097]]

Initial Loss: 39.41053393699553

Updated Kernel:
 [[ 1.61612313 -0.61997865 -0.53639399]
 [-1.08119086  0.85718539 -2.30976093]
 [ 1.73658953 -0.76942914  0.31081686]]

Updated FC Weights:
 [[-0.24937038]
 [ 1.46210794]
 [-1.12096006]
 [-0.3224172 ]
 [-0.38405435]
 [ 1.83219101]
 [-1.09989127]
 [ 0.00808479]
 [-0.87785842]]

Final Output:
 [[1.]]

Final Loss: 3.0814879110195774e-31
